namespace Platform.Services.Storage.Helpers;

public class FileRenameHelper
{
    public static string Rename(string name) =>
        name.Replace("\"", "")
            .Replace("@", "")
            .Replace("!", "")
            .Replace("#", "")
            .Replace("$", "")
            .Replace("%", "")
            .Replace("^", "")
            .Replace("&", "")
            .Replace("*", "")
            .Replace("(", "")
            .Replace(")", "")
            .Replace("-", "")
            .Replace("+", "")
            .Replace("_", "")
            .Replace("=", "")
            .Replace("{", "")
            .Replace("}", "")
            .Replace("[", "")
            .Replace("]", "")
            .Replace(";", "")
            .Replace("'", "")
            .Replace("<", "")
            .Replace(">", "")
            .Replace(":", "")
            .Replace("\'", "")
            .Replace("`", "")
            .Replace("~", "")
            .Replace("|", "")
            .Replace("?", "")
            .Replace(".", "")
            .Replace(",", "")
            .Replace("\\", "")
            .Replace("Ö", "o")
            .Replace("ö", "o")
            .Replace("Ğ", "g")
            .Replace("ğ", "g")
            .Replace("Ə", "e")
            .Replace("ə", "e")
            .Replace("I", "i")
            .Replace("ı", "i")
            .Replace("Ü", "u")
            .Replace("ü", "u")
            .Replace("Ş", "s")
            .Replace("ş", "s")
            .Replace("Ç", "c")
            .Replace("ç", "c")
            .Replace("~", "")
            .Replace("+", "")
            .Replace("$", "");
}
